name: CICD
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          submodules: recursive
          repository: Zheng-Yi-git/GIF-doc
          token: ***
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          set-safe-directory: true
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
          name: github-pages
          retention-days: 1
      - run: chmod -c -R +rX "$INPUT_PATH" | while read line; do 
              echo "::warning title=Invalid file permissions automatically fixed::$line"
              done
              tar \
                --dereference --hard-dereference \
                --directory "$INPUT_PATH" \
                -cvf "$RUNNER_TEMP/artifact.tar" \
                --exclude=.git \
                --exclude=.github \
                .
      - uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: /home/runner/work/_temp/artifact.tar
          retention-days: 1
          if-no-files-found: warn
  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: gh api -X POST "repos/$GITHUB_REPOSITORY/pages/telemetry" \
              -F github_run_id="$GITHUB_RUN_ID" \
              -F conclusion="$CONCLUSION"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
        with:
          emit_telemetry: false
          token: ***
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: github-pages
          preview: false
